//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkWithBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderBooks
    {
        public System.Guid ID_order_book { get; set; }
        public System.Guid ID_order { get; set; }
        public System.Guid ID_book { get; set; }
        public int Quantity { get; set; }
        public decimal Unit_price { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
